Feature 163666888 support req and res
nanek/pn-logging pull request #25
Opened 2019-02-27 23:14 UTC by sandinmyjoints

@ahaurw01 

I believe these are the last pieces of winex that Neodarwin uses that pn-logging did not support.

2019-02-27 23:21 UTC, sandinmyjoints commented on test/index.js
> +      log = new index.Log({
This diff hunk is prettier.

2019-02-28 16:56 UTC, ahaurw01 requested changes
I don't think the addition of `req` and `res` like this quite fits the different API that pn-logging exposes. 

Projects that use pn-logging typically have one `Log` instance that is created using the configured options for the environment. For example, sd-playground has a `logging` module that exports a `new Log(config.get('logging'))`. Then that singleton instance is used throughout the project to fire off `.info(...)`, `.error(...)`, etc. We'd be at risk of having one `req` object get applied to totally unrelated log entries, I believe. If neodarwin doesn't use a singleton then we might be ok in practice, but it might lead to confusion and bugs in the future.

Maybe instead we extend the logging methods somehow? E.g. `log.info(msg, meta, error, req, res)`.

2019-02-28 17:02 UTC, sandinmyjoints commented
Thanks -- you're right, this is a winex solution but not right for pn-logging. I'll rework it.

2019-02-28 18:20 UTC, sandinmyjoints commented
@ahaurw01 BTY.

2019-02-28 20:44 UTC, ahaurw01 approved these changes
Looks good!

2019-02-28 20:57 UTC, merged